name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type Check
        run: npm run build
      
      - name: Lint Check (if available)
        run: npm run lint --if-present
        continue-on-error: true

  build-test:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, macos-13]  # ARM64 and x86 macOS only
    
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Frontend
        run: npm run build
      
      - name: Check Rust
        working-directory: ./src-tauri
        run: |
          cargo check
          cargo clippy -- -D warnings
          cargo test